# Generated by Django 4.2.1 on 2023-05-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0003_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('info', models.TextField(max_length=5000)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
