# Generated by Django 4.2.1 on 2023-05-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0005_aboutcompany_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Communication',
        ),
    ]
