# Generated by Django 4.2.1 on 2023-05-08 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0006_rename_contacts_communication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='phone1',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+7*********'. Допустимая длина номер 9 цифр.", regex='^\\+?1?\\d{9}$')]),
        ),
    ]
