# Generated by Django 4.2.1 on 2023-05-08 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0007_alter_communication_phone1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='phone2',
        ),
        migrations.AddField(
            model_name='communication',
            name='city_phone',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+7-7212-XX-XX-XX'.", regex='^\\+7-\\d{4}-\\d{2}-\\d{2}-\\d{2}$')]),
        ),
        migrations.AddField(
            model_name='communication',
            name='phone',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+7-7XX-XXX-XX-XX'.", regex='^\\+7-\\d{3}-\\d{3}-\\d{2}-\\d{2}$')]),
        ),
    ]
