# Generated by Django 4.2.1 on 2023-05-09 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0008_remove_communication_phone1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcompany',
            options={'verbose_name': 'about company', 'verbose_name_plural': 'about company'},
        ),
        migrations.AlterModelOptions(
            name='communication',
            options={'verbose_name': 'communication', 'verbose_name_plural': 'communication'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'сontact', 'verbose_name_plural': 'сontacts'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='text',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='adress',
            field=models.CharField(max_length=255, verbose_name='adress'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='city_phone',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+7-7212-XX-XX-XX'.", regex='^\\+7-\\d{4}-\\d{2}-\\d{2}-\\d{2}$')], verbose_name='city phone'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='location',
            field=models.CharField(max_length=55, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='phone',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+7-7XX-XXX-XX-XX'.", regex='^\\+7-\\d{3}-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='news',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='news',
            name='info',
            field=models.TextField(max_length=5000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='area',
            field=models.CharField(max_length=50, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='client',
            field=models.CharField(max_length=50, verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='project_image', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.PositiveIntegerField(blank=True, verbose_name='price'),
        ),
    ]
