# Generated by Django 4.2.1 on 2023-05-09 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0009_alter_aboutcompany_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechsupportAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.contact')),
            ],
        ),
    ]
