# Generated by Django 4.2.1 on 2023-05-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0010_techsupportanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('reviewed', 'reviewed')], default='pending', max_length=10, verbose_name='status'),
        ),
    ]
