# Generated by Django 4.2.1 on 2023-05-10 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0011_alter_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='city_phone',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="The phone number must be in the format: '+7-7212-XX-XX-XX'.", regex='^\\+7-\\d{4}-\\d{2}-\\d{2}-\\d{2}$')], verbose_name='city phone'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='phone',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="The phone number must be in the format: '+7-7XX-XXX-XX-XX'.", regex='^\\+7-\\d{3}-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='phone'),
        ),
    ]
