# Generated by Django 4.2.1 on 2023-05-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0013_alter_aboutcompany_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='set_services',
            field=models.IntegerField(choices=[('Мобильная разработка', 1), ('Веб разработка', 2), ('Маркетинг', 3)], null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_image/'),
        ),
    ]
